server {
    listen 80;
    server_name ump.test;

    # 1. Aponta para a pasta com os arquivos do WP
    root /var/www/html;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # 2. Aponta as requisições PHP para o contêiner do WordPress
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_intercept_errors on;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
